name: jupyter_tutorial_rydberg
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.19.1
  - scipy=1.5.2
  - matplotlib=3.3.2
  - qutip=4.5.2
  - notebook
  - jupyter_contrib_nbextensions
  - ipympl
  - ipython
  - git
  - pip:
    - krotov==1.2.0
